import { Vulnerability } from './supabase';
import { computeCompliance } from './compliance';

export type EvidencePackage = {
  generatedAt: string;
  organization: string;
  auditPeriod: { from: string; to: string };
  summary: {
    soc2Overall: number;
    openVulns: number;
    resolvedVulns: number;
    totalVulns: number;
  };
  soc2Criteria: { id: string; label: string; score: number; openCount: number; criticalCount: number }[];
  nistFunctions: { id: string; label: string; score: number; openCount: number }[];
  cisControls: { id: string; label: string; score: number; openCount: number; criticalCount: number }[];
  findings: {
    id: string;
    title: string;
    severity: string;
    status: string;
    asset: string;
    cve_id: string;
    mitre_tactic: string;
    cis_control: string;
    remediation: string;
    created_at: string;
  }[];
  attestation: string;
};

/**
 * F-15: Build a SOC2-ready compliance evidence package
 * from the current vulnerability data.
 */
export function buildEvidencePackage(
  vulns: Vulnerability[],
  organization: string,
  auditPeriodDays = 90
): EvidencePackage {
  const result = computeCompliance(vulns);
  const now = new Date();
  const from = new Date(now.getTime() - auditPeriodDays * 24 * 60 * 60 * 1000);

  return {
    generatedAt: now.toISOString(),
    organization,
    auditPeriod: {
      from: from.toISOString().split('T')[0],
      to: now.toISOString().split('T')[0],
    },
    summary: {
      soc2Overall: result.soc2Overall,
      openVulns: result.openVulns,
      resolvedVulns: result.resolvedVulns,
      totalVulns: result.totalVulns,
    },
    soc2Criteria: result.soc2Rows.map(r => ({
      id: r.id, label: r.label, score: r.score,
      openCount: r.openCount, criticalCount: r.criticalCount,
    })),
    nistFunctions: result.nistRows.map(r => ({
      id: r.id, label: r.label, score: r.score, openCount: r.openCount,
    })),
    cisControls: result.cisRows.map(r => ({
      id: r.id, label: r.label, score: r.score,
      openCount: r.openCount, criticalCount: r.criticalCount,
    })),
    findings: vulns.map(v => ({
      id: v.id,
      title: v.title,
      severity: v.severity,
      status: v.status,
      asset: v.asset,
      cve_id: v.cve_id || '',
      mitre_tactic: v.mitre_tactic || '',
      cis_control: v.cis_control || '',
      remediation: v.remediation,
      created_at: v.created_at,
    })),
    attestation: `This report was automatically generated by Sentinel AI on ${now.toUTCString()}. It documents the security posture of ${organization} based on ${vulns.length} vulnerability records assessed during the audit period ${from.toISOString().split('T')[0]} to ${now.toISOString().split('T')[0]}.`,
  };
}

/**
 * F-15: Generate a Markdown evidence report for SOC2 auditors.
 */
export function buildEvidenceMarkdown(pkg: EvidencePackage): string {
  const sev = (s: string) => ({ critical: '🔴', high: '🟠', medium: '🟡', low: '🔵', info: '⚪' }[s] ?? '⚪');

  const lines = [
    `# Security Compliance Evidence Report`,
    `**Organization:** ${pkg.organization}`,
    `**Audit Period:** ${pkg.auditPeriod.from} → ${pkg.auditPeriod.to}`,
    `**Generated:** ${new Date(pkg.generatedAt).toUTCString()}`,
    ``,
    `---`,
    ``,
    `## Executive Summary`,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| SOC 2 Readiness | ${pkg.summary.soc2Overall}% |`,
    `| Open Findings | ${pkg.summary.openVulns} |`,
    `| Resolved Findings | ${pkg.summary.resolvedVulns} |`,
    `| Total Assessed | ${pkg.summary.totalVulns} |`,
    ``,
    `---`,
    ``,
    `## SOC 2 Trust Services Criteria`,
    ``,
    `| Control | Label | Score | Open | Critical |`,
    `|---------|-------|-------|------|----------|`,
    ...pkg.soc2Criteria.map(r => `| ${r.id} | ${r.label} | ${r.score}% | ${r.openCount} | ${r.criticalCount} |`),
    ``,
    `---`,
    ``,
    `## NIST Cybersecurity Framework`,
    ``,
    `| Function | Label | Score | Open |`,
    `|----------|-------|-------|------|`,
    ...pkg.nistFunctions.map(r => `| ${r.id} | ${r.label} | ${r.score}% | ${r.openCount} |`),
    ``,
    `---`,
    ``,
    `## CIS Controls v8`,
    ``,
    `| Control | Label | Score | Open | Critical |`,
    `|---------|-------|-------|------|----------|`,
    ...pkg.cisControls.map(r => `| ${r.id} | ${r.label} | ${r.score}% | ${r.openCount} | ${r.criticalCount} |`),
    ``,
    `---`,
    ``,
    `## All Findings (${pkg.findings.length})`,
    ``,
    ...pkg.findings.map(f =>
      `### ${sev(f.severity)} [${f.severity.toUpperCase()}] ${f.title}\n` +
      `- **Status:** ${f.status}\n` +
      `- **Asset:** \`${f.asset}\`\n` +
      (f.cve_id ? `- **CVE:** ${f.cve_id}\n` : '') +
      (f.mitre_tactic ? `- **MITRE:** ${f.mitre_tactic}\n` : '') +
      (f.cis_control ? `- **CIS:** ${f.cis_control}\n` : '') +
      `- **Remediation:** ${f.remediation}\n` +
      `- **Detected:** ${new Date(f.created_at).toLocaleDateString()}\n`
    ),
    `---`,
    ``,
    `## Attestation`,
    ``,
    pkg.attestation,
    ``,
    `*Generated by Sentinel AI — santinelai.online*`,
  ];

  return lines.join('\n');
}

/**
 * F-23: Trigger browser print dialog for PDF export.
 * Opens a new window with print-optimized HTML.
 */
export function printReportAsPDF(title: string, markdownContent: string): void {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${title}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 11pt; line-height: 1.6; color: #1e293b; padding: 40px; max-width: 900px; margin: 0 auto; }
  h1 { font-size: 22pt; color: #0f172a; margin-bottom: 8px; border-bottom: 3px solid #10b981; padding-bottom: 12px; }
  h2 { font-size: 14pt; color: #10b981; margin: 24px 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
  h3 { font-size: 11pt; color: #1e293b; margin: 16px 0 4px; font-weight: 600; }
  p, li { margin-bottom: 4px; }
  strong { font-weight: 600; }
  code { font-family: monospace; background: #f1f5f9; padding: 1px 4px; border-radius: 3px; font-size: 9pt; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0 16px; font-size: 9pt; }
  th { background: #f8fafc; font-weight: 600; text-align: left; padding: 6px 10px; border: 1px solid #e2e8f0; }
  td { padding: 5px 10px; border: 1px solid #e2e8f0; }
  tr:nth-child(even) td { background: #f8fafc; }
  hr { border: none; border-top: 1px solid #e2e8f0; margin: 20px 0; }
  .header-meta { color: #64748b; font-size: 10pt; margin-bottom: 4px; }
  .badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-size: 8pt; font-weight: 600; }
  @page { margin: 20mm; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
<pre id="raw" style="display:none">${markdownContent.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
<div id="content"></div>
<script>
// Minimal markdown to HTML converter
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
const md = document.getElementById('raw').textContent;
const lines = md.split('\\n');
let html = '';
let inTable = false;
for (const line of lines) {
  if (line.startsWith('# ')) { html += '<h1>' + esc(line.slice(2)) + '</h1>'; continue; }
  if (line.startsWith('## ')) { html += '<h2>' + esc(line.slice(3)) + '</h2>'; continue; }
  if (line.startsWith('### ')) { html += '<h3>' + esc(line.slice(4)) + '</h3>'; continue; }
  if (line.startsWith('---')) { html += '<hr>'; continue; }
  if (line.startsWith('|')) {
    if (!inTable) { html += '<table>'; inTable = true; }
    const cells = line.split('|').slice(1,-1).map(c => c.trim());
    if (cells.every(c => /^[-:]+$/.test(c))) continue;
    const tag = !inTable || (html.endsWith('<table>')) ? 'th' : 'td';
    html += '<tr>' + cells.map(c => '<' + tag + '>' + esc(c) + '</' + tag + '>').join('') + '</tr>';
    continue;
  }
  if (inTable) { html += '</table>'; inTable = false; }
  if (line.startsWith('- **')) {
    html += '<p>' + esc(line).replace(/\\*\\*([^*]+)\\*\\*/g, '<strong>$1</strong>').replace(/\`([^\`]+)\`/g, '<code>$1</code>') + '</p>';
    continue;
  }
  if (line.startsWith('**')) {
    html += '<p class="header-meta">' + esc(line).replace(/\\*\\*([^*]+)\\*\\*/g, '<strong>$1</strong>') + '</p>';
    continue;
  }
  if (line.trim() === '') { html += '<br>'; continue; }
  html += '<p>' + esc(line) + '</p>';
}
if (inTable) html += '</table>';
document.getElementById('content').innerHTML = html;
setTimeout(() => window.print(), 400);
</script>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
  }
}
