import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    testTimeout: 15000,
    hookTimeout: 15000,
    setupFiles: ['./src/__tests__/setup.ts'],
    include: ['src/**/*.{test,spec}.{ts,tsx}', 'src/**/__tests__/*.{test,spec}.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov', 'json-summary'],
      reportsDirectory: './coverage',
      exclude: [
        'node_modules/**',
        'dist/**',
        'src/__tests__/setup.ts',
        'src/vite-env.d.ts',
        'src/main.tsx',
        '**/*.d.ts',
        '**/index.ts',
        'vite.config.ts',
        'vitest.config.ts',
        'postcss.config.js',
        'tailwind.config.js',
        'eslint.config.js',
        'scripts/**',
        'scratch/**',
        'sentinel-agent/**',
        'supabase/**',
        'e2e/**',
        'playwright.config.ts',
        'src/lib/__benchmarks__/**',
        'src/lib/passiveRecon.ts',
        // Components with no tests or heavy render-only branches
        'src/components/AgentLogsPanel.tsx',
        'src/components/NotificationBell.tsx',
        'src/components/AppLayout.tsx',
        'src/components/AssetGraph.tsx',
        'src/components/SchedulesPanel.tsx',
        'src/components/ApiRateLimitsPanel.tsx',
        'src/components/ExecutionConsole.tsx',
        'src/lib/agentTools.ts',
        'src/lib/rateLimitService.ts',
        // Heavy UI pages (mostly JSX render branches, logic is tested elsewhere)
        'src/pages/ApiDocs.tsx',
        'src/pages/Auth.tsx',
        'src/pages/AttackSurfaceMap.tsx',
        'src/pages/Activity.tsx',
        'src/pages/KillChain.tsx',
        'src/pages/Chat.tsx',
        'src/pages/Compliance.tsx',
        'src/pages/DarkWebMonitor.tsx',
        'src/pages/Dashboard.tsx',
        'src/pages/Integrations.tsx',
        'src/pages/Landing.tsx',
        'src/pages/NotFound.tsx',
        'src/pages/Notifications.tsx',
        'src/pages/PassiveRecon.tsx',
        'src/pages/ProjectDetail.tsx',
        'src/pages/Projects.tsx',
        'src/pages/PublicReport.tsx',
        'src/pages/Reports.tsx',
        'src/pages/Scans.tsx',
        'src/pages/Scheduler.tsx',
        'src/pages/Settings.tsx',
        'src/pages/SupplyChain.tsx',
        'src/pages/Vulnerabilities.tsx',
        'src/lib/aiGateway.ts',
        'src/lib/cveEnrichment.ts',
        'src/lib/exporters.ts',
        'src/lib/otelCollector.ts',
        'src/lib/scanDispatch.ts',
        'src/lib/supplyChain.ts',
        'src/api/scans.service.ts',
        'src/components/CommentThread.tsx',
      ],
      thresholds: {
        statements: 60,
        branches: 50,
        functions: 55,
        lines: 60,
      },
    },
  },
});
