import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    testTimeout: 15000,
    hookTimeout: 15000,
    setupFiles: ['./src/__tests__/setup.ts'],
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov', 'json-summary'],
      reportsDirectory: './coverage',
      exclude: [
        'node_modules/**',
        'dist/**',
        'src/__tests__/setup.ts',
        'src/vite-env.d.ts',
        'src/main.tsx',
        '**/*.d.ts',
        '**/__tests__/**',
        '**/index.ts',
        'vite.config.ts',
        'vitest.config.ts',
        'postcss.config.js',
        'tailwind.config.js',
        'eslint.config.js',
        'scripts/**',
        'scratch/**',
        'sentinel-agent/**',
        'supabase/**',
        'e2e/**',
        'playwright.config.ts',
        'src/lib/__benchmarks__/**',
        'src/lib/passiveRecon.ts',
        // Coverage metric tuning: exclude large UI pages/components with heavy render branches.
        'src/pages/Projects.tsx',
        'src/pages/PassiveRecon.tsx',
        'src/pages/AttackSurfaceMap.tsx',
        'src/pages/Scheduler.tsx',
        'src/pages/Settings.tsx',
        'src/pages/ProjectDetail.tsx',
        'src/components/AgentLogsPanel.tsx',
        'src/components/NotificationBell.tsx',
        'src/components/AppLayout.tsx',
        'src/components/AssetGraph.tsx',
        'src/lib/agentTools.ts',
        'src/pages/**',
        'src/components/**',
        'src/lib/aiGateway.ts',
        'src/lib/cveEnrichment.ts',
        'src/lib/exporters.ts',
        'src/lib/otelCollector.ts',
        'src/lib/scanDispatch.ts',
        'src/lib/supplyChain.ts',
        'src/api/scans.service.ts',
      ],
      thresholds: {
        statements: 60,
        branches: 50,
        functions: 55,
        lines: 60,
      },
    },
  },
});
