-- BACKWARD_COMPATIBLE: YES
-- REASON: Adds nullable columns share_token, is_public to eports. Old INSERT/SELECT unaffected.
-- ROLLBACK: ALTER TABLE reports DROP COLUMN IF EXISTS share_token, DROP COLUMN IF EXISTS is_public;
/*
  # Public sharing for reports

  1. Schema changes
    - Add `share_token` (uuid, unique, nullable) to `reports` — used as opaque key for public links
    - Add `is_public` (boolean, default false) to `reports` — toggles anonymous read access
  2. Security
    - New RLS policy lets anon + authenticated users SELECT a report only when `is_public = true`
    - Existing owner policies remain untouched
  3. Notes
    - Tokens are generated by the app on enable; revoke = set is_public = false (token kept for potential re-enable)
    - Unique index ensures tokens are collision-free
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'reports' AND column_name = 'share_token'
  ) THEN
    ALTER TABLE reports ADD COLUMN share_token uuid;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'reports' AND column_name = 'is_public'
  ) THEN
    ALTER TABLE reports ADD COLUMN is_public boolean NOT NULL DEFAULT false;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS reports_share_token_key ON reports (share_token) WHERE share_token IS NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'reports' AND policyname = 'Public reports are readable by anyone'
  ) THEN
    CREATE POLICY "Public reports are readable by anyone"
      ON reports FOR SELECT
      TO anon, authenticated
      USING (is_public = true AND share_token IS NOT NULL);
  END IF;
END $$;
