import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Layout, Plus } from 'lucide-react';
export const ScanHeader = ({ projects, selectedProjectId, currentMode = 'UNKNOWN', onSelectProject, onNewScan }) => {
    return (_jsxs("div", { className: "flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold text-white mb-2", children: "Vulnerability Scans" }), _jsx("p", { className: "text-slate-400", children: "Manage and monitor security assessments across your infrastructure." })] }), _jsxs("div", { className: "flex flex-wrap items-center gap-3", children: [_jsxs("div", { className: `px-3 py-1.5 rounded-full text-xs font-semibold border ${currentMode === 'REAL'
                            ? 'text-emerald-300 border-emerald-500/30 bg-emerald-500/10'
                            : currentMode === 'MOCK'
                                ? 'text-amber-300 border-amber-500/30 bg-amber-500/10'
                                : 'text-slate-300 border-slate-600/50 bg-slate-800/50'}`, children: ["Mode: ", currentMode] }), _jsxs("div", { className: "relative", children: [_jsx(Layout, { className: "absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" }), _jsxs("select", { "aria-label": "Select project", title: "Select project", value: selectedProjectId || '', onChange: (e) => onSelectProject(e.target.value), className: "pl-10 pr-8 py-2.5 bg-slate-800/50 border border-slate-700 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 appearance-none min-w-[200px]", children: [_jsx("option", { value: "", children: "Select Project..." }), projects.map(p => (_jsx("option", { value: p.id, children: p.name }, p.id)))] })] }), _jsxs("button", { onClick: onNewScan, "aria-label": "Start a new scan", title: "Start a new scan", className: "flex items-center gap-2 px-5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl transition-all shadow-lg shadow-blue-900/20", children: [_jsx(Plus, { className: "w-4 h-4" }), _jsx("span", { children: "New Scan" })] })] })] }));
};
